name = "MUSEAddCubes"
uuid = "ceaf603d-0922-48eb-b57c-44a4b5c63512"
authors = ["Jarle Brinchmann"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
